services:
  zookeeper:
    image: zookeeper:3.9.2

  kafka:
    image: bitnami/kafka:3.7.0
    ports:
      - "${KAFKA_EXPOSE_PORT}:${KAFKA_EXPOSE_PORT}"
    expose:
      - 9092
    environment:
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9092,OUTSIDE://localhost:${KAFKA_EXPOSE_PORT}
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_LISTENERS: INSIDE://kafka:9092,OUTSIDE://0.0.0.0:${KAFKA_EXPOSE_PORT}
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
  kafka-init:
    image: bitnami/kafka:3.7.0
    user: root
    command: sh -c "apt-get update && apt-get -y install jq && sh /tmp/kafka/kafka_topic_init.sh"
    volumes:
        - ../scripts/kafka/kafka_topic.json:/tmp/kafka/kafka_topic.json
        - ../scripts/kafka/kafka_topic_init.sh:/tmp/kafka/kafka_topic_init.sh
    init: true
